[package]
name = "coin_flip"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
version = "1.1"

[dependencies]
openplay_core= { git = "git@github.com:OpenPlay-Technologies/openplay-core.git", subdir = "package", rev = "v1.1" }

[addresses]
coin_flip = "0x0"