[package]
name = "coin_flip"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
version = "3"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.61.2" }
openplay_core= { git = "git@github.com:OpenPlay-Technologies/openplay-core.git", subdir = "package", rev = "v3.1" }

[addresses]
coin_flip = "0x0"